DROP USER biblioteca CASCADE;

CREATE USER biblioteca IDENTIFIED BY biblioteca 
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
quota 10m ON users;

GRANT CREATE SESSION TO
biblioteca;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER
TO biblioteca;

GRANT CREATE SEQUENCE TO biblioteca;


